services:
  auth-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql

  social-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    ports:
      - "5434:5432"
    volumes:
      - social_pgdata:/var/lib/postgresql

  matchmaking-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matchmaking_db
    ports:
      - "5435:5432"
    volumes:
      - matchmaking_pgdata:/var/lib/postgresql

  nats:
    image: nats:2.11-alpine
    restart: unless-stopped
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  nats-box:
    image: natsio/nats-box:latest
    depends_on:
      - nats
    volumes:
      - ./docker/nats:/nats:ro
    command: ["sh", "/nats/script.sh"]

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - auth-db
      - social-db
      - matchmaking-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexus.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  auth_pgdata:
  matchmaking_pgdata:
  pgadmin_data:
  redisinsight_data:
  social_pgdata:
